name: Lint

on:
  pull_request:
    types: [opened, synchronize]
  check_run:
    types: [requested_action]

jobs:
  report_eslint_action:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: gatsby/.github/actions/gatsby-eslint-reporter@lintaction
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
